### ISSUE TITLE
no such file or directory decompiler_compiled

### ISSUE THREAD

**Issue by taylorgag** [nevillegrech/gigahorse-toolchain#10] opened 2021-03-29 01:32 UTC
Sorry to bother you，when I install as instructed，there is no mistake.But when I run the command  ./gigahorse.py examples/long_running.hex，there is a mistake called compile error and no such file or directory decompiler_compiled.

**Comment by sifislag** [comment] 2021-03-29 09:38
Hi,
What souffle version do you have? It will not work with older versions. We recommend release version `2.0.2`.

**Comment by taylorgag** [comment] 2021-03-29 10:04
Well，yeah！The version I am using is 2.0.2



---Original---
From: "Sifis ***@***.***&gt;
Date: Mon, Mar 29, 2021 17:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nevillegrech/gigahorse-toolchain] no such file or directory decompiler_compiled (#10)




 
Hi,
 What souffle version do you have? It will not work with older versions. We recommend release version 2.0.2.

**Comment by sifislag** [comment] 2021-03-29 10:05
Can you post the entire console output of your command?

**Comment by taylorgag** [comment] 2021-03-29 10:46
After using this command "./gigahorse.py examples/long_running.hex" ,the outputs are shown in those two pictures.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nevillegrech/gigahorse-toolchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 晚上6:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nevillegrech/gigahorse-toolchain] no such file or directory decompiler_compiled (#10)





 
Can you post the entire console output of your command?

**Comment by sifislag** [comment] 2021-03-29 11:28
I'm sorry I can't see any pictures with your message.

**Comment by taylorgag** [comment] 2021-03-29 11:49
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nevillegrech/gigahorse-toolchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 晚上7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nevillegrech/gigahorse-toolchain] no such file or directory decompiler_compiled (#10)





 
I'm sorry I can't see any pictures with your message.

**Comment by sifislag** [comment] 2021-03-29 11:52
Can you try using the web client or copy pasting the console output instead of sending the image?

**Comment by taylorgag** [comment] 2021-03-29 12:08
./gigahorse.py examples/long_running.hex
Compiling /home/wangben/111/gigahorse-toolchain-master/logic/decompiler.dl to C++ program and executable
Warning: Variable newContext only occurs once in file transactional-context.dl at line 110
MergeContext(ctx, caller, newContext) :-
--------------------------^--------------
Warning: No rules/facts defined for relation StorageContents in file decompiler_output.dl at line 87
.decl StorageContents(addr: symbol, contents: symbol)
------^-----------------------------------------------
Warning: No rules/facts defined for relation SHA3Decompositions in file decompiler_output.dl at line 90
.decl SHA3Decompositions(addr: symbol, base1: symbol, base2: symbol, offset: symbol)
------^------------------------------------------------------------------------------
compiler error: cannot compile source file /home/wangben/111/gigahorse-toolchain-master/cache/e1a51bae89187a563f68592507944a6f.cpp
g++ -std=c++17&nbsp;&nbsp; -fwrapv&nbsp; -DUSE_NCURSES&nbsp; -O3 -DUSE_LIBZ&nbsp; -DUSE_SQLITE&nbsp; -fopenmp&nbsp; -march=native&nbsp; -std=c++17 -Wdate-time -D_FORTIFY_SOURCE=2 -o/home/wangben/111/gigahorse-toolchain-master/cache/e1a51bae89187a563f68592507944a6f /home/wangben/111/gigahorse-toolchain-master/cache/e1a51bae89187a563f68592507944a6f.cpp&nbsp; -ldl -lpthread -lsqlite3 -lz -lncurses -lfunctors&nbsp; -I/usr/bin/../include -I/usr/bin/include 
g++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs&gt; for instructions.
failed to compile C++ source </home/wangben/111/gigahorse-toolchain-master/cache/e1a51bae89187a563f68592507944a6f.cpp&gt;
Process Process-1:
Traceback (most recent call last):
&nbsp; File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
&nbsp;&nbsp;&nbsp; self.run()
&nbsp; File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
&nbsp;&nbsp;&nbsp; self._target(*self._args, **self._kwargs)
&nbsp; File "./gigahorse.py", line 240, in compile_datalog
&nbsp;&nbsp;&nbsp; assert not(process.returncode), "Compilation failed. Stopping."
AssertionError: Compilation failed. Stopping.
Traceback (most recent call last):
&nbsp; File "./gigahorse.py", line 474, in <module&gt;
open(v, 'r') # check program exists
FileNotFoundError: [Errno 2] No such file or directory: 'decompiler_compiled'





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nevillegrech/gigahorse-toolchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nevillegrech/gigahorse-toolchain] no such file or directory decompiler_compiled (#10)





 
Can you try using the web client or copy pasting the console output instead of sending the image?

**Comment by taylorgag** [comment] 2021-03-29 12:45
Have you received this output?I truly hope you can solve this problem for me.Thanks a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nevillegrech/gigahorse-toolchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nevillegrech/gigahorse-toolchain] no such file or directory decompiler_compiled (#10)





 
Can you try using the web client or copy pasting the console output instead of sending the image?

**Comment by sifislag** [comment] 2021-03-29 13:14
This looks like a g++ compilation error of the program generated by souffle. I can confirm that it works for me using `g++ 9.3.0`. What version do you have?
You can also try adding the `-i` flag in your  command. This runs our decompilation using souffle's interpreted mode, skipping producing and compiling a c++ program. On my PC it decompiles `long_running.hex` in 2.35 seconds.

**Comment by taylorgag** [comment] 2021-03-29 13:28
Thanks for your warm apply.The g++ version which I am using is 7.5.0(Ubuntu comes with it).I will try to update this version .As for your second suggestion, I used the command&nbsp; &nbsp;./gigahorse.py -i examples/long_running.hex   ,
it finally has its own output and has written results to results.json.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nevillegrech/gigahorse-toolchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nevillegrech/gigahorse-toolchain] no such file or directory decompiler_compiled (#10)





 
This looks like a g++ compilation error of the program generated by souffle. I can confirm that it works for me using g++ 9.3.0. What version do you have?
 You can also try adding the -i flag in your  command. This runs our decompilation using souffle's interpreted mode, skipping producing and compiling a c++ program. On my PC it decompiles long_running.hex in 2.35 seconds.

**Comment by sifislag** [comment] 2021-03-29 14:08
Glad I could help!
Let us know if you could manage to solve it by updating g++. Otherwise I'll close this issue in a few hours since it is an issue with souffle and its dependencies.

**Comment by taylorgag** [comment] 2021-03-30 09:24
By updating g++ to version 9.3.0,I already solved this problem.Thanks for your warm suggestions.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "nevillegrech/gigahorse-toolchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 晚上10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nevillegrech/gigahorse-toolchain] no such file or directory decompiler_compiled (#10)





 
Glad I could help!
 Let us know if you could manage to solve it by updating g++. Otherwise I'll close this issue in a few hours since it is an issue with souffle and its dependencies.

**Closed** 2021-03-30 09:26 UTC
